name: econobook
description: EconoBook MVP
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.0.0
  cloud_firestore: ^6.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/logo/